# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/d6d5739d-a5fc-40ea-b500-4b62d7ff2353";
      fsType = "ext4";
    };

  fileSystems."/mnt/samsung_1tb" = {
    device = "/dev/disk/by-uuid/60289233-acfa-467d-a301-facb4e83f4ae";
    fsType = "ext4";
  };  

  fileSystems."/mnt/lexar_2tb" = {
    device = "/dev/disk/by-uuid/8208f463-50df-46e8-86e6-cf979f06c350";
    fsType = "ext4";
  };

  fileSystems."/mnt/ntfs_370G" = {
    device = "/dev/disk/by-uuid/536CF6A7517F0562";
    fsType = "ntfs";
  };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp4s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "performance";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # Reduce swappiness
  boot.kernel.sysctl = { "vm.swappiness" = 10;};

}
